### ISSUE TITLE
外国人向けのホームページを雑に開設する

### ISSUE THREAD

**Issue by yutokyokutyo** [MICS-NAGOYA/development#18]
https://international-sports-nagoya.jimdofree.com/

**Comment by yutokyokutyo** [comment]
日本にいる英語を学びたい日本人・日本にいる日本語を学びたい外国人による国内留学。
MICS基盤により、スポーツと人を通して仲良くなり、場を作る。

**Comment by kurotaky** [comment]
jimdo便利だな.. MICS基盤良い 👍
